#!/bin/bash

cat <<EOF
export INPUT=`echo {1}`
export DIMS=`echo ${2}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                 Transform AFNI MNI-space ROIs to EPI space'
echo ''
echo '   - Resamples '${INPUT}' mask data to MNI space at '${DIMS}'^3mm,'
echo '   - Transforms whole-brain masks to MNI space,'
echo '   - Creates 1 concatenated run per participant in run order.'
echo ''
echo '************************************************************************'

cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # invert EPI_to_TAL
        cat_matvec mat_EPI_to_TAL.aff12.1D -I > mat_TAL_to_EPI.aff12.1D

        # register runs with MNI
        if [ ! -f ${SESS}/anat_mask_MNI2EPI.${ID}.nii.gz ]; then
            3dAllineate \
                -prefix ${SESS}/anat_mask_MNI2EPI.${ID}.nii.gz \
                -input ${SESS}/${INPUT}.nii.gz \
                -1Dmatrix_apply ${SESS}/mat_TAL_to_EPI.aff12.1D \
                -master ${SESS}/anat_EPI_brain.nii.gz \
                -float \
                -final NN \
                -mast_dxyz ${DIMS} ${DIMS} ${DIMS}
        fi
    done
done

cd ${DIR_PIPE}

EOF
