#!/bin/bash

cat <<EOF
export INPUT=$(echo func_${1})

EOF

cat <<"EOF"
echo '*** MODULE: deoblique. Alters image to have no obliquity (AFNI only). ***'

# loop through sessions
DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do

    # loop through runs
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`
        FILE=`echo ${RUN}/*.nii.gz`

        if [ ! -f ${SESS}/func_ob.${ID}.${NUM}.nii.gz ]; then
            if [ ${NUM} == '01' ]; then
                # deoblique run (unconstrained for first run)
                3dWarp \
                    -prefix ${SESS}/func_ob.${ID}.${NUM}.nii.gz \
                    -deoblique \
                    -quintic \
                    -verb \
                    ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz > \
                    ${SESS}/PARAMS/deoblique.${ID}.${NUM}.1D

            else
                # deoblique run, matching dimensions to first run
                3dWarp \
                   -prefix ${SESS}/func_ob.${ID}.${NUM}.nii.gz \
                   -deoblique \
                   -quintic \
                   -verb \
                   -gridset ${SESS}/func_ob.${ID}.01.nii.gz \
                   ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz > \
                   ${SESS}/PARAMS/deoblique.${ID}.${NUM}.1D
            fi
        fi
    done
done

EOF
