#!/bin/bash

cat <<EOF
export INPUT=$(echo func_${1})
export POLORT=${2}

EOF

cat <<"EOF"
echo '*** MODULE: detrend. Detrends all inputs to order n, retaining the mean.*'

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        if [ ! -f ${SESS}/func_detrend.${ID}.${NUM}.nii.gz ]; then

            # produce mean
            3dTstat \
                -prefix ${SESS}/func_mean.${ID}.${NUM}.nii.gz \
                -mean ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz

            # detrend data
            3dDetrend \
                -prefix ${SESS}/func_tmp_detrend.${ID}.${NUM}.nii.gz \
                -polort ${POLORT} \
                ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz

            # add mean back into detrended data
            3dcalc \
                -prefix ${SESS}/func_detrend.${ID}.${NUM}.nii.gz \
                -a ${SESS}/func_tmp_detrend.${ID}.${NUM}.nii.gz \
                -b ${SESS}/func_mean.${ID}.${NUM}.nii.gz \
                -expr 'a+b'
        fi
    done
done

EOF
