#!/bin/bash

cat <<EOF
export DATA_QUALITY=`echo ${1}`
export COST=`echo ${2}`
export REG_DOF=`echo ${3}`

EOF

cat <<"EOF"
echo '*** MODULE: linreg_calc_afni. Calculates EPI <--> T1 <--> MNI152. *******'

# Copy MNI brain to experiment directory
if [ ! -f ${DIR_DATA}/${DIR_EXPT}/anat_MNI.nii.gz ]; then
    3dcopy ${DIR_AFNI}/MNI_avg152T1+tlrc ${DIR_DATA}/${DIR_EXPT}/anat_MNI.nii.gz
fi

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    SESS=`basename ${SESS}`
    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1`

    # Set EPI data file (for low vs high quality data).
    if [ ${DATA_QUALITY} = 'low' ]; then
        EPI_BRAIN=`echo ${DIR}/${SESS}/anat_EPI_initTR_brain.nii.gz`
    else
        EPI_BRAIN=`echo ${DIR}/${SESS}/anat_EPI_brain.nii.gz`
    fi

    if [ ! -f ${DIR}/${SESS}/reg_EPI_to_T1.nii.gz ]; then
        
        # Copy of EPI and MNI brain for @auto_tlrc.
        if [ ! -f anat_EPI_brain+orig* ]; then 3dcopy ${EPI_BRAIN} anat_EPI_brain; fi
        if [ ! -f template* ]; then 3dcopy ${DIR_AFNI}/MNI_avg152T1+tlrc template; fi
        if [ ! -f anat_T1_brain+orig* ]; then
            # register to the session T1 if exists, else, use the first session.
            if [ `ls -l ${DIR} | grep ^d | wc -l` -eq `ls -l ${DIR_T1} | grep ^d | wc -l` ]; then
                3dcopy ${DIR_T1}/${SESS}/anat_T1_brain.nii.gz anat_T1_brain
            else
                3dcopy ${DIR_T1}/SESS01/anat_T1_brain.nii.gz anat_T1_brain
            fi
        fi

        # Talarac individual brain, turning off skullstrip.
        @auto_tlrc \
            -base template+tlrc \
            -input anat_T1_brain+orig \
            -no_ss \
            -maxite 300 \
            -OK_maxite \
            -init_xform AUTO_CENTER

        align_epi_anat.py \
            -anat anat_T1_brain+orig \
            -epi anat_EPI_brain+orig \
            -epi_base 0 -epi2anat \
            -suffix EPI_to_T1 \
            -anat_has_skull no \
            -epi_strip None \
            -volreg off \
            -tshift off \
            -${REG_DOF} \
            -tlrc_apar anat_T1_brain+tlrc \
            -ex_mode quiet \
            -cost ${COST}

        # Move outputs from /tmp back into data folders folders.
        mv anat_EPI_brainEPI_to_T1_tlrc_mat.aff12.1D ${DIR}/${SESS}/mat_EPI_to_TAL.aff12.1D
        mv anat_EPI_brainEPI_to_T1_mat.aff12.1D ${DIR}/${SESS}/mat_EPI_to_T1.aff12.1D
        mv anat_T1_brainEPI_to_T1_mat.aff12.1D ${DIR}/${SESS}/mat_T1_to_EPI.aff12.1D

        # create T1 to TAL pathway
        cat_matvec \
            ${DIR}/${SESS}/mat_T1_to_EPI.aff12.1D \
            ${DIR}/${SESS}/mat_EPI_to_TAL.aff12.1D > \
            ${DIR}/${SESS}/mat_T1_to_TAL.aff12.1D
        
        if [ ! -f ${DIR}/${SESS}/reg_T1_to_TAL.nii.gz ]; then
            3dcopy anat_T1_brain+tlrc ${DIR}/${SESS}/reg_T1_to_TAL.nii.gz
        fi
        
        if [ ! -f ${DIR}/SESS01/reg_EPI_to_T1.nii.gz ]; then
            # copy the session T1 registration if exists, else, use the first session.
            if [ `ls -l ${DIR} | grep ^d | wc -l` -eq `ls -l ${DIR_T1} | grep ^d | wc -l` ]; then
                3dcopy anat_EPI_brainEPI_to_T1+orig ${DIR}/${SESS}/reg_EPI_to_T1.nii.gz
            else
                3dcopy anat_EPI_brainEPI_to_T1+orig ${DIR}/SESS01/reg_EPI_to_T1.nii.gz
            fi
        fi
    fi

    # Create reg_T1_to_EPI
    if [ ! -f ${DIR}/${SESS}/reg_T1_to_EPI.nii.gz ]; then
        # generate EPI_to_T1
        if [ `ls -l ${DIR} | grep ^d | wc -l` -eq `ls -l ${DIR_T1} | grep ^d | wc -l` ]; then
            3dAllineate \
                -prefix ${DIR}/${SESS}/reg_T1_to_EPI.nii.gz \
                -input ${DIR_T1}/${SESS}/anat_T1_brain.nii.gz \
                -1Dmatrix_apply ${DIR}/${SESS}/mat_T1_to_EPI.aff12.1D \
                -master ${EPI_BRAIN} \
                -float -quiet \
                -final quintic
        else
            3dAllineate \
                -prefix ${DIR}/${SESS}/reg_T1_to_EPI.nii.gz \
                -input ${DIR_T1}/SESS01/anat_T1_brain.nii.gz \
                -1Dmatrix_apply ${DIR}/${SESS}/mat_T1_to_EPI.aff12.1D \
                -master ${EPI_BRAIN} \
                -float -quiet \
                -final quintic
        fi                
    fi
done

EOF
