#!/bin/bash

cat <<EOF
export INPUT=$(echo func_${1})

EOF

cat<<"EOF"
echo '*** MODULE: surf2vol. Projects surface data into single subject volume. *'

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    SESS=`basename ${SESS}`
    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/${SESS}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1/${SESS}`
    DIR_FS=`echo ${SUBJECTS_DIR}/${DIR_EXPT}_${SUB}_${SESS}`
    FS_NAME=`echo ${DIR_EXPT}_${SUB}_${SESS}`

    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`
    
        if [ ! -f ${DIR}/func_ctx.${ID}.${NUM}.nii.gz ]; then
            # project surface data --> volume
            3dSurf2Vol \
              -prefix ${DIR}/func_tmp_ctx.R.${ID}.${NUM}.nii.gz \
              -spec ${DIR_FS}/SUMA/${FS_NAME}_both.spec \
              -surf_A ${DIR_FS}/SUMA/rh.white.asc \
              -sv ${DIR_FS}/SUMA/${FS_NAME}_SurfVol_Alnd_Exp+orig. \
              -grid_parent ${DIR}/func_scaled.${ID}.${NUM}.nii.gz \
              -map_func ave \
              -f_steps 15 \
              -f_index nodes \
              -sdata ${DIR}/${INPUT}.R.${ID}.${NUM}.niml.dset

            3dSurf2Vol \
              -prefix ${DIR}/func_tmp_ctx.L.${ID}.${NUM}.nii.gz \
              -spec ${DIR_FS}/SUMA/${FS_NAME}_both.spec \
              -surf_A ${DIR_FS}/SUMA/lh.white.asc \
              -sv ${DIR_FS}/SUMA/${FS_NAME}_SurfVol_Alnd_Exp+orig. \
              -grid_parent ${DIR}/func_scaled.${ID}.${NUM}.nii.gz \
              -map_func ave \
              -f_steps 15 \
              -f_index nodes \
              -sdata ${DIR}/${INPUT}.L.${ID}.${NUM}.niml.dset

            # add all volumes to create smoothed cortical dataset
            3dcalc \
              -prefix ${DIR}/func_ctx.${ID}.${NUM}.nii.gz \
              -a ${DIR}/func_tmp_ctx.R.${ID}.${NUM}.nii.gz \
              -b ${DIR}/func_tmp_ctx.L.${ID}.${NUM}.nii.gz \
              -expr 'a+b'
        fi
    done
done

EOF
