#!/bin/bash

cat <<EOF
export INPUT=`echo 'func_${1}'`
export DIMS=`echo ${2}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                     FSL MNI-to-EPI transform data'
echo ''
echo '   - Resamples '${INPUT}' data to MNI space at '${DIMS}'^3mm,'
echo '   - Transforms whole-brain masks to MNI space,'
echo '   - Creates 1 concatenated run per participant in run order.'
echo ''
echo '************************************************************************'

cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in `basename ${DIR_SESS}`; do
    
    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/${SESS}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1/${SESS}`

    DIR_RUNS=`ls -d -- ${DIR}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # register runs with individual T1s
        if [ ! -f ${DIR}/func_T1.${ID}.${NUM}.nii.gz ]; then
            flirt -in ${DIR}/${INPUT}.${ID}.${NUM}.nii.gz \
                  -ref ${DIR}/anat_EPI_brain.nii.gz \
                  -applyxfm -init ${DIR}/mat_MNI_to_EPI.mat \
                  -out ${DIR}/func_MNI2EPI.${ID}.${NUM}.nii.gz
                  -interp sinc \
                  -sincwidth 7 \
                  -sincwindow blackman
        fi
    done
done

cd ${DIR_PIPE}

EOF
