#!/bin/bash

cat <<EOF
export INPUT=`echo 'func_${1}'`
export DIMS=`echo ${2}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                       FSL MNI-transform data'
echo ''
echo '   - Resamples '${INPUT}' data to MNI space at '${DIMS}'^3mm,'
echo '   - Transforms whole-brain masks to MNI space,'
echo '   - Creates 1 concatenated run per participant in run order.'
echo ''
echo '************************************************************************'

cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in `basename ${DIR_SESS}`; do
    
    DIR=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/${SESS}`
    DIR_T1=`echo ${DIR_DATA}/${DIR_EXPT}/${SUB}/T1/${SESS}`


    if [ ! -f ${DIR}/anat_EPI_reg_target.nii.gz ]; then
        # create registration dummy for FSL
        3dresample \
            -dxyz ${DIMS} ${DIMS} ${DIMS} \
            -prefix ${DIR}/anat_EPI_reg_target.nii.gz \
            -inset ${DIR_T1}/anat_T1_brain.nii.gz
    fi

    DIR_RUNS=`ls -d -- ${DIR}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # register runs with individual T1s
        if [ ! -f ${DIR}/func_MNI.${ID}.${NUM}.nii.gz ]; then
            flirt \
                -in ${DIR}/${INPUT}.${ID}.${NUM}.nii.gz \
                -ref ${DIR}/anat_EPI_reg_target.nii.gz \
                -applyxfm -init ${DIR}/mat_EPI_to_TAL.mat \
                -out ${DIR}/func_MNI.${ID}.${NUM}.nii.gz
                -interp sinc \
                -sincwidth 7 \
                -sincwindow blackman
        fi
    done

    # register session masks with MNI
    if [ ! -f ${DIR}/${SESS}/anat_EPI_mask_MNI-linreg.nii.gz ]; then
        flirt \
            -in ${DIR}/${SESS}/anat_EPI_mask.nii.gz \
            -ref ${DIR}/${SESS}/anat_EPI_reg_target.nii.gz \
            -applyxfm -init ${DIR}/${SESS}/mat_EPI_to_TAL.mat \
            -interp nearestneighbour \
            -out ${DIR}/${SESS}/anat_EPI_mask_MNI-linreg.nii.gz
    fi
done

cd ${DIR_PIPE}

EOF
