#!/bin/bash

cat <<EOF
export INPUT=`echo 'func_'${1}`
export DIMS=`echo ${2}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                       AFNI MNI-transform data'
echo ''
echo '   - Resamples '${INPUT}' data to MNI space at '${DIMS}'^3mm,'
echo '   - Transforms whole-brain masks to MNI space,'
echo '   - Creates 1 concatenated run per participant in run order.'
echo ''
echo '************************************************************************'


cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # register runs with MNI
        if [ ! -f ${SESS}/func_MNI-lin.${ID}.${NUM}.nii.gz ]; then
            3dAllineate \
                -prefix ${SESS}/func_MNI-lin.${ID}.${NUM}.nii.gz \
                -input ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz \
                -1Dmatrix_apply ${SESS}/mat_EPI_to_TAL.aff12.1D \
                -master ${DIR_AFNI}/MNI_avg152T1+tlrc \
                -float \
                -final wsinc5 \
                -mast_dxyz ${DIMS} ${DIMS} ${DIMS}
        fi
    done
    
    # register session masks with MNI
    if [ ! -f ${SESS}/anat_EPI_mask_MNI-lin.nii.gz ]; then
        3dAllineate \
            -prefix ${SESS}/anat_EPI_mask_MNI-lin.nii.gz \
            -input ${SESS}/anat_EPI_mask.nii.gz \
            -1Dmatrix_apply ${SESS}/mat_EPI_to_TAL.aff12.1D \
            -master ${DIR_AFNI}/MNI_avg152T1+tlrc \
            -float \
            -final NN \
            -mast_dxyz ${DIMS} ${DIMS} ${DIMS}
    fi
done

# create group EPI mask in MNI space
3dMean \
    -datum short \
    -prefix ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz \
    ${DIR_DATA}/${DIR_EXPT}/*/${DATA_TYPE}/*/anat_EPI_mask_MNI-lin.nii.gz

3dcalc \
    -a ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz \
    -expr 'step(a-0.999)' \
    -prefix ${DIR_DATA}/${DIR_EXPT}/anat_EPI_mask_MNI-lin_group.nii.gz

rm ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz

cd ${DIR_PIPE}

EOF
