#!/bin/bash

cat <<EOF
export INPUT=`echo 'func_'${1}`
export MASK=`echo 'anat_'${2}`
export FILTER=`echo ${3}`
export CUTOFF=`echo ${4}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                          Low-Pass Module'
echo ''
echo '   - Low-passes masked functional data using a '${FILTER}' filter.'
echo ''
echo '************************************************************************'

cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        if [ ! -f ${SESS}/func_lowpass.${ID}.${NUM}.nii.gz ]; then
            
            # set input paths
            FUNC=`echo ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz`
            ANAT=`echo ${SESS}/${MASK}.nii.gz`

            # lowpass data
            epi-lowpass \
                ${FILTER} \
                ${FUNC} \
                ${ANAT} \
                ${CUTOFF} \
                ${SESS} \
                ${ID} \
                ${NUM}
        fi
    done
done

cd ${DIR_PIPE}

EOF
