#!/bin/bash

cat <<EOF
export INPUT=`echo 'func_'${1}`
export DIMS=`echo ${2}`

EOF

cat <<"EOF"

echo '************************************************************************'
echo '                  Nonlinear: AFNI MNI-transform data'
echo ''
echo '   - Resamples '${INPUT}' data to MNI space at '${DIMS}'^3mm,'
echo '   - Transforms whole-brain masks to MNI space,'
echo ''
echo '************************************************************************'


cd /tmp

DIR_SESS=`ls -d -- ${DIR_DATA}/${DIR_EXPT}/${SUB}/${DATA_TYPE}/*/`
for SESS in ${DIR_SESS}; do
    DIR_RUNS=`ls -d -- ${SESS}/RUN*`
    for RUN in ${DIR_RUNS}; do
        NUM=`basename ${RUN} | sed 's/[^0-9]//g'`

        # register runs with MNI (concatenates linear transform)
        if [ ! -f ${SESS}/func_MNI-nonlin.${ID}.${NUM}.nii.gz ]; then
            3dNwarpApply \
                -prefix ${SESS}/func_MNI-nonlin.${ID}.${NUM}.nii.gz \
                -source ${SESS}/${INPUT}.${ID}.${NUM}.nii.gz \
                -master WARP \
                -dxyz ${DIMS} \
                -nwarp ${SESS}/reg_nlin_TAL_WARP.nii.gz \
                       ${SESS}/mat_EPI_to_TAL.aff12.1D
        fi
    done
    
    # register session masks with MNI (concatenates linear transform)
    if [ ! -f ${SESS}/anat_EPI_mask_MNI-nonlin.nii.gz ]; then
        3dNwarpApply \
            -prefix ${SESS}/anat_EPI_mask_MNI-nonlin.nii.gz \
            -source ${SESS}/anat_EPI_mask.nii.gz \
            -master WARP \
            -dxyz ${DIMS} \
            -ainterp NN \
            -nwarp ${SESS}/reg_nlin_TAL_WARP.nii.gz \
                   ${SESS}/mat_EPI_to_TAL.aff12.1D
    fi
done

# create group EPI mask in MNI space
3dMean \
    -datum short \
    -prefix ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz \
    ${DIR_DATA}/${DIR_EXPT}/*/${DATA_TYPE}/*/anat_EPI_mask_MNI-nonlin.nii.gz

3dcalc \
    -a ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz \
    -expr 'step(a-0.999)' \
    -prefix ${DIR_DATA}/${DIR_EXPT}/anat_EPI_mask_MNI-nonlin_group.nii.gz

rm ${DIR_DATA}/${DIR_EXPT}/tmp_mean.nii.gz

cd ${DIR_PIPE}

EOF
