# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import re
import sys
from packaging.version import Version

from datman import __packagename__, __version__, __copyright__

sys.path.append(os.path.abspath(
    os.path.join(os.path.dirname(__file__), 'sphinxext')))
from github_link import make_linkcode_resolve


# -- Project information -----------------------------------------------------

project = __packagename__
copyright = __copyright__
author = "TIGRLab"

# The short X.Y version
version = Version(__version__).public
# The full version, including alpha/beta/rc tags
release = version


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.doctest',
    'sphinx.ext.githubpages',
    'sphinx.ext.ifconfig',
    'sphinx.ext.intersphinx',
    'sphinx.ext.linkcode',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'sphinxcontrib.apidoc'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Extension configuration -------------------------------------------------

apidoc_module_dir = '../datman'
apidoc_output_dir = 'api'
apidoc_excluded_paths = ['bids/*']
apidoc_separate_modules = True
apidoc_extra_args = ['--module-first', '-d 1', '-T']

# Options for github links
# The following is used by sphinx.ext.linkcode to provide links to github
linkcode_resolve = make_linkcode_resolve('datman',
                                         'https://github.com/tigrlab/'
                                         'datman/blob/{revision}/'
                                         '{package}/{path}#L{lineno}')

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}

# -- Options for versioning extension ----------------------------------------
scv_show_banner = True
scv_whitelist_branches = ('master', re.compile(r'^docs\/.*$'), 'test_docs')
scv_whitelist_tags = (
    re.compile(r'^\d{2,}\..*$'),
    re.compile(r'^[1-9]\..*$'),
    re.compile(r'^0\.\d{2,}\..*$'),
    re.compile(r'^0\.[2-9]\..*$'),
)
